### ISSUE TITLE
Use proper casing for filenames

### ISSUE THREAD

**Issue by JacobSamro** [pradeephareeshph/machine-learning-and-advanced#1]
As per google style guide http://google.github.io/styleguide/pyguide.html#3164-guidelines-derived-from-guidos-recommendations It's better to name files with using underscores instead of spaces. Its not suggested to name files names in camel casing.

So your files will become 
`1_data_preprocessing/1_importing_all.py`

Refer this repo : https://github.com/aymericdamien/TensorFlow-Examples/tree/master/examples

**Comment by pradeephareeshph** [comment]
Okay, Will Do that.
